projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        dev:
          url: "http://localhost:4000"
        prod:
          url: ""
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: "database/prisma.yml"
